/**
 * 
 */
package com.cross.plateform.common.rpc.core.codec.impl;

import com.cross.plateform.common.rpc.core.codec.CommonRpcEncoder;
import com.google.protobuf.Message;
/**
 * @author liubing1
 *
 */
public class ProtocolBufEncoder implements CommonRpcEncoder {

	/* (non-Javadoc)
	 * @see com.jd.cross.plateform.rocketrpc.core.codec.RocketRPCEncoder#encode(java.lang.Object)
	 */
	@Override
	public byte[] encode(Object object) throws Exception {
		// TODO Auto-generated method stub
		if (!(object instanceof Message)) {
			throw new Exception(
					"Send object is not type of com.google.protobuf.Message,pls sure the object is generated by pb,object is: "
							+ object);
		}
		Message message = (Message) object;
		return message.toByteArray();
	}

}
